name = "WaterModels"
uuid = "7c60b362-08f4-5b14-8680-cd67a3e18348"
authors = ["Byron Tasseff"]
repo = "https://github.com/lanl-ansi/WaterModels.jl"
version = "0.8.0"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PolyhedralRelaxations = "2e741578-48fa-11ea-2d62-b52c946f73a0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
InfrastructureModels = "~0.6, 0.7"
Interpolations = "~0.12, 0.13"
JSON = "~0.18, 0.19, 0.20, 0.21"
JuMP = "~0.21"
MathOptInterface = "~0.9"
Memento = "~1"
PolyhedralRelaxations = "~0.3"
julia = "^1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cbc", "Ipopt", "Juniper", "Logging", "Test"]
