name = "WaterModels"
uuid = "7c60b362-08f4-5b14-8680-cd67a3e18348"
authors = ["Byron Tasseff"]
repo = "https://github.com/lanl-ansi/WaterModels.jl"
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"

[compat]
InfrastructureModels = "~0.3.0"
JuMP = "≥ 0.19.0"
julia = "≥ 1.0.0"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Cbc", "Ipopt", "Juniper"]
